homeSuccess:
  customize:
    noticeUnreadDiaryComment:
      template: [diary, noticeUnreadDiaryComment]
      is_component: true
      parts:    [information]
      target:   [bottom]
    homeLinks:
      template: [diary, homeLinks]
      is_component: false
      parts:    [invite]
      target:   [before]
    friendDiaryList:
      template: [diary, friendDiaryList]
      is_component: true
      parts:    [profileEdit]
      target:   [before]
    myDiaryList:
      template: [diary, myDiaryList]
      is_component: true
      parts:    [profileEdit]
      target:   [before]
profileSuccess:
  customize:
    memberDiaryList:
      template: [diary, memberDiaryList]
      is_component: true
      parts:    [communityList]
      target:   [after]
