homeSuccess:
  customize:
    noticeUnreadDiaryComment:
      template: [diary, noticeUnreadDiaryComment]
      is_component: true
      parts   : [information]
      target  : [bodyBottom]
profileSuccess:
  customize:
    memberDiaryList:
      template: [diary, memberDiaryList]
      is_component: true
      parts:    [profile]
      target:   [after]
