homeSuccess:
  customize:
    friendDiaryList:
      parts:    [homeTopSampleBox]
      target:   [after]
    myDiaryList:
      parts:    [homeTopSampleBox]
      target:   [after]
profileSuccess:
  customize:
    memberDiaryList:
      parts:    [profile]
      target:   [after]
